version: 2.1
orbs:
  node: circleci/node@5
jobs:
  install-and-persist:
    executor: cypress/default
    steps:
      - cypress/install
      - persist_to_workspace:
          paths:
              - .cache/Cypress
              - project
          root: ~/  
  run-tests:
    executor: cypress/default
    steps:
      - attach_workspace:
          at: ~/
      - cypress/run-tests:
          cypress-command: npx cypress run --record --key a7898ec2-3282-41d1-bc8e-31af4c545c1f
workflows:
  cy-test:
    jobs:
      - run-tests:
          requires:
            - install-and-persist
