version: 2.1

parameters:
  run_on_master:
    type: string
    default: "master"

x-branch-filter: &branch_filter
  filters:
    branches:
      only: << pipeline.parameters.run_on_master >>

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  install-and-persist:
    executor: cypress/default
    steps:
      - cypress/install
      - persist_to_workspace:
          paths:
              - .cache/Cypress
              - project
          root: ~/  
  run-tests:
    executor: cypress/default
    steps:
      - attach_workspace:
          at: ~/
      - cypress/run-tests:
          cypress-command: npx cypress run --record --key 8b1354f4-34f4-444e-a610-387819f489df

workflows:
  cy-test:
    jobs:
      - install-and-persist:           
          filters:
            branches:
              only:
                - master
      - run-tests:
          requires: 
            - install-and-persist
          filters:
            branches:
              only:
                - master

triggers:
  - schedule:
      cron: "30 12 * * *" # This runs at 10:30 PM AEST (12:30 PM UTC)
      filters:
        branches:
          only:
            - master
