version: 2.1

x-filter: &global_filter
  filters:
    branches:
      only: << pipeline.parameters.run_on_master >>

parameters:
  run_on_master:
    type: string
    default: "master"

orbs:
  cypress: cypress-io/cypress@3.3.1
jobs:
  install-and-persist:
    executor: cypress/default
    steps:
      - cypress/install
      - persist_to_workspace:
          paths:
              - .cache/Cypress
              - project
          root: ~/  
  run-tests:
    executor: cypress/default
    steps:
      - attach_workspace:
          at: ~/
      - cypress/run-tests:
          cypress-command: npx cypress run --record --key 8b1354f4-34f4-444e-a610-387819f489df
workflows:
  cy-test:
    jobs:
    - install-and-persist: 
        <<: *global_filter
    - run-tests:
        requires: 
          - install-and-persist
        <<: *global_filter
    triggers:
      - schedule:
          cron: "0 0 * * *"
          <<: *global_filter

    
          