version: 2.1

parameters:
  run_on_master:
    type: string
    default: "master"

x-branch-filter:
  filters:
    branches:
      only: << pipeline.parameters.run_on_master >>

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  install-and-persist:
    executor: cypress/default
    steps:
      - cypress/install
      - persist_to_workspace:
          paths:
            - .cache/Cypress
            - project
          root: ~/
  run-tests:
    executor: cypress/default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Create .envDB file
          command: |
            echo "MONGO_URI=$MONGO_URI" > ./env_files/.envDB
            echo "DB_NAME=$DB_NAME" >> ./env_files/.envDB
            echo "COLLECTION_NAME=$COLLECTION_NAME" >> ./env_files/.envDB
      - run:
          name: Echo Environment Variables
          command: |
            echo "ENV_FILE: $ENV_FILE"
            echo "MONGO_URI: $MONGO_URI"
            echo "DB_NAME: $DB_NAME"
            echo "COLLECTION_NAME: $COLLECTION_NAME"
      - cypress/run-tests:
          # parallelism: 2 # Uses 2 parallel instances
          cypress-command: npx cypress run  \
            --env ENV_FILE=.envDB \
            --record --key 9df61a48-6409-465a-9846-7f2fec12399e

workflows:
  cy-test:
    jobs:
      - install-and-persist:
          filters:
            branches:
              only:
                - master
      - run-tests:
          requires:
            - install-and-persist
          filters:
            branches:
              only:
                - master

triggers:
  - schedule:
      cron: "30 12 * * *" # This runs at 10:30 PM AEST (12:30 PM UTC)
      filters:
        branches:
          only:
            - master
